from typing import Protocol
from uuid import UUID
import numpy as np

class FaceRepository(Protocol):
    def upsert(self, aluno_id: UUID, embedding: np.ndarray) -> None: ...
    def nearest(self, embedding: np.ndarray) -> tuple[UUID, float] | None: ...
    def delete(self, aluno_id: UUID) -> None: ...
